package modelo.entidad;
// Generated 20 oct. 2022 21:02:22 by Hibernate Tools 4.3.1



/**
 * TipoLibro generated by hbm2java
 */
public class TipoLibro  implements java.io.Serializable {


     private Integer idTipoLibro;
     private String descTipo;

    public TipoLibro() {
    }

    public TipoLibro(String descTipo) {
       this.descTipo = descTipo;
    }
   
    public Integer getIdTipoLibro() {
        return this.idTipoLibro;
    }
    
    public void setIdTipoLibro(Integer idTipoLibro) {
        this.idTipoLibro = idTipoLibro;
    }
    public String getDescTipo() {
        return this.descTipo;
    }
    
    public void setDescTipo(String descTipo) {
        this.descTipo = descTipo;
    }




}


